apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
  description: Guests Group
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  title: Team A
  description: The A Team
spec:
  type: team
  parent: engineering
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-b
  title: Team B
  description: The B Team
spec:
  type: team
  parent: engineering
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: engineering
  title: Engineering
  description: The Engineering Department
spec:
  type: department
  children: [team-a, team-b]
